import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
const public_Sans = Public_Sans({ subsets: ["latin"] });
import styles from "./layout.module.scss";
import "@styles/components.scss";
import Sidebar from "../components/sidebar";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${styles.body} ${public_Sans.className}`}>
        <Sidebar />
        <main className={styles.main}>
          <Header />
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
